### ISSUE TITLE
Zaprojektowanie UI zadawania pytań przez studentów i odbierania pytań przez wykładowcę

### ISSUE THREAD

**Issue by Derstilon** [michal367/OI-Project#148]
1. Szkic widoku zadawania pytań
2. Szkic widoku pytań zadanych widocznych u wykładowcy
3. Szkic wyglądu powiadomień o nowym pytaniu
4. Lista parametrów jakie mają mieć obiekty przesyłane w ramach wysyłania pytania przez studenta

PROPOZYCJA:
spam protection 1 min ?
opcja bez spam protection ale nie anonimowe?
opcja zablokowania adresata anonimowego pytania po stronie wykładowcy?

**Comment by Petros9** [comment]
![propozycja_wykładowca.png](https://images.zenhubusercontent.com/6051e28764b1845049ead693/84f4480f-a62d-4318-9660-d23ed1fe28cd)

**Comment by Petros9** [comment]
a obiekty mają mieć treść, godzinę zadania pytania i nick użytkownika
albo jego imię i nazwisko

**Comment by Petros9** [comment]
![porpozycje.png](https://images.zenhubusercontent.com/6051e28764b1845049ead693/991e96ba-d886-4596-9ff2-295b5555d4d4)
