### ISSUE TITLE
Wybór szaty graficznej projketu 

### ISSUE THREAD

**Issue by ostatni5** [michal367/OI-Project#39]

**Comment by Derstilon** [comment]
![image.png](https://images.zenhubusercontent.com/6051e2c1cde27761f6d0d97b/fcacc7cd-5600-46fa-8dd2-dd6195b70d71)
Wstępna propozycja

**Comment by Derstilon** [comment]
primary: {
            light: "#E1F1FF",
            main: "#80A3E4",
            dark: "#4870AC",
        },
        secondary: {
            light: "#FFEECB",
            main: "#D9A21B",
            dark: "#877455",
        },

**Comment by Derstilon** [comment]
![image.png](https://images.zenhubusercontent.com/6051e2c1cde27761f6d0d97b/8f06eba0-8b01-449f-876e-feb04423d811)
