### ISSUE TITLE
Wybór one język dla our project xD

### ISSUE THREAD

**Issue by ostatni5** [michal367/OI-Project#52]
Musimy ustalić gdzie w jakim języku piszemy bo zaraz będzie polglish everywhere.

**Comment by Derstilon** [comment]
Readme po polsku, UI po polsku
kod, commity, pull requesty po angielsku

**Comment by ostatni5** [comment]
Polski: Issue, Epic (Zenhub), UI
Angielski: Readme, Kod, Commity, Pull request
